post http://localhost:3002/register
Content-Type: application/json

{ 
    "name":"vishal",
    "username":"visvarma2", 
    "password":"vrv123456", 
    "gender":"male"
 }

###


post http://localhost:3001/login
Content-Type: application/json

{ 
   "username":"visvarma2", 
   "password":"vrv123456"
}